### ISSUE TITLE
Attempt to index local 'timestamp' error

### ISSUE THREAD

**Issue by Xouzoura** [Ramilito/kubectl.nvim#2]
Getting a weird issue when calling with <space+k> (E5108: Error executing lua: .../share/nvim/lazy/kubectl.nvim/lua/kubectl/utils/time.lua:6: attempt to index local 'timestamp'), somehow the timestamp is undefined. Attaching an image as well

![Screenshot from 2024-05-28 21-33-02](https://github.com/Ramilito/kubectl.nvim/assets/74069598/4876a1f7-57b6-48c2-a572-a90e8a4a3198)

**Comment by Ramilito** [comment]
That's super weird, that can only mean that there is a resource (pod) that doesn't have the ```metadata.creationTimestamp``` set.
I added a check so that the plugin doesn't crash, would love to see what value you have in there though!

**Comment by yingzhu146** [comment]
Had same issue - print debugging indicated it returned a `vim.nil` of type `userdata` instead of a string so parsing failed

**Comment by yetone** [comment]
&lt;img width="662" alt="image" src="https://github.com/Ramilito/kubectl.nvim/assets/1206493/7921d2d9-78f8-42d2-ba6c-84ef0f4390c2">

Have upgraded to the latest version, but still have the same issue

**Comment by Ramilito** [comment]
@yetone Could you post the error as well? Need to verify the line this happens on

**Comment by yetone** [comment]
<img width="1163" alt="image" src="https://github.com/Ramilito/kubectl.nvim/assets/1206493/cfb031dd-856c-40bd-aca6-58b0f13a1be1">

**Comment by Ramilito** [comment]
Thank you @yetone!
I was surprised when that field was missing in [#1] but now it seems we get a non-string value even. I've added a check to not process that field if it's not a string.
The plugin should work now I hope, but I'm concerned about the output, would you mind trying to update and see if the restarts or age column display nil.
 
Compare that to what you get when running ```kubectl get pods -o=json```, find the pod that gets nil value and check the ```metadata.creationTimestamp```

**Comment by Xouzoura** [comment]
https://github.com/Ramilito/kubectl.nvim/issues/2#issuecomment-2136010440 
I've updated and still the same issue. Is there some way to help or some dump that would help? Thanks again, awesome idea for plugin

**Comment by Ramilito** [comment]
I did another try in fixing this so if this doesn't fix it I'd love the help in finding the issue.
If you use Lazy to load the plugin, there is a pretty easy way to debug this.
1. clone this repo somewhere on disk, keep note of the path
2. add ```dir = "~/<path>",``` where you load the plugin
3. go to the file ```~/<path>/lua/kubectl/pods/init.lua```
4. function M.getRestarts on row 111 is the problem.
5. comment out the row 121 and the plugin should work.
6. to debug, add a ```print(value.lastState.terminated.finishedAt))``` and see what weird values you get.

Sorry but I haven't implemented enough tests and debug level yet, will add both of them to the TODO list.

**Comment by Xouzoura** [comment]
Haha no worries. It works. Thanks a lot for the help, love the plugin so far, great job!
